import {
  Airplane,
  AirplaneTilt,
  ArrowUUpLeft,
  ArrowUUpRight,
  ArrowsClockwise,
  ArrowsLeftRight,
  Baby,
  Backpack,
  Balloon,
  Bank,
  Barbell,
  Basket,
  Basketball,
  Bathtub,
  BeerBottle,
  Bell,
  Bicycle,
  Boat,
  Book,
  Books,
  Brain,
  Bread,
  Briefcase,
  Broom,
  Buildings,
  Bus,
  Cake,
  Calendar,
  Camera,
  Car,
  Carrot,
  Cat,
  Certificate,
  Champagne,
  ChartLineUp,
  ChartPieSlice,
  Church,
  Cigarette,
  Clock,
  CloudRain,
  Coffee,
  Coins,
  Confetti,
  Cookie,
  CreditCard,
  DeviceMobile,
  Diamond,
  Dog,
  DotsThree,
  Dress,
  Drop,
  Egg,
  Eye,
  FilmSlate,
  Fire,
  FirstAid,
  Flower,
  ForkKnife,
  GameController,
  GasPump,
  Gavel,
  Gear,
  Gift,
  Globe,
  GraduationCap,
  Hamburger,
  Hammer,
  HandCoins,
  Handbag,
  Handshake,
  Heart,
  Heartbeat,
  House,
  HouseLine,
  IceCream,
  Key,
  Leaf,
  Lightbulb,
  Lightning,
  Lock,
  Martini,
  Money,
  Motorcycle,
  Mountains,
  MusicNotes,
  Note,
  Notebook,
  Package,
  Palette,
  PawPrint,
  PencilSimple,
  PersonSimpleRun,
  PiggyBank,
  Pill,
  Pizza,
  Plant,
  Plug,
  Question,
  Receipt,
  Repeat,
  Scales,
  Scissors,
  ShoppingBag,
  ShoppingCart,
  Shower,
  Signature,
  Sneaker,
  SoccerBall,
  Star,
  Stethoscope,
  Storefront,
  Student,
  Sun,
  Sunglasses,
  TShirt,
  Tag,
  Taxi,
  Television,
  Ticket,
  Toolbox,
  Tooth,
  Train,
  Trash,
  Tree,
  TrendDown,
  TrendUp,
  Umbrella,
  User,
  UserCircle,
  Users,
  Vault,
  Wallet,
  Warehouse,
  Watch,
  WifiHigh,
  Wine,
  Wrench,
} from "@phosphor-icons/react/dist/ssr";
import { cn } from "@/lib/utils";

type PhosphorIcon = typeof House;

/**
 * Icons are stored on a category, account or person as a Phosphor name.
 * Explicit map rather than a namespace import so the bundle only carries what
 * we actually use, and an unknown name degrades to a tag instead of crashing.
 */
const ICONS: Record<string, PhosphorIcon> = {
  Airplane,
  AirplaneTilt,
  ArrowUUpLeft,
  ArrowUUpRight,
  ArrowsClockwise,
  ArrowsLeftRight,
  Baby,
  Backpack,
  Balloon,
  Bank,
  Barbell,
  Basket,
  Basketball,
  Bathtub,
  BeerBottle,
  Bell,
  Bicycle,
  Boat,
  Book,
  Books,
  Brain,
  Bread,
  Briefcase,
  Broom,
  Buildings,
  Bus,
  Cake,
  Calendar,
  Camera,
  Car,
  Carrot,
  Cat,
  Certificate,
  Champagne,
  ChartLineUp,
  ChartPieSlice,
  Church,
  Cigarette,
  Clock,
  CloudRain,
  Coffee,
  Coins,
  Confetti,
  Cookie,
  CreditCard,
  DeviceMobile,
  Diamond,
  Dog,
  DotsThree,
  Dress,
  Drop,
  Egg,
  Eye,
  FilmSlate,
  Fire,
  FirstAid,
  Flower,
  ForkKnife,
  GameController,
  GasPump,
  Gavel,
  Gear,
  Gift,
  Globe,
  GraduationCap,
  Hamburger,
  Hammer,
  HandCoins,
  Handbag,
  Handshake,
  Heart,
  Heartbeat,
  House,
  HouseLine,
  IceCream,
  Key,
  Leaf,
  Lightbulb,
  Lightning,
  Lock,
  Martini,
  Money,
  Motorcycle,
  Mountains,
  MusicNotes,
  Note,
  Notebook,
  Package,
  Palette,
  PawPrint,
  PencilSimple,
  PersonSimpleRun,
  PiggyBank,
  Pill,
  Pizza,
  Plant,
  Plug,
  Question,
  Receipt,
  Repeat,
  Scales,
  Scissors,
  ShoppingBag,
  ShoppingCart,
  Shower,
  Signature,
  Sneaker,
  SoccerBall,
  Star,
  Stethoscope,
  Storefront,
  Student,
  Sun,
  Sunglasses,
  TShirt,
  Tag,
  Taxi,
  Television,
  Ticket,
  Toolbox,
  Tooth,
  Train,
  Trash,
  Tree,
  TrendDown,
  TrendUp,
  Umbrella,
  User,
  UserCircle,
  Users,
  Vault,
  Wallet,
  Warehouse,
  Watch,
  WifiHigh,
  Wine,
  Wrench,
};

export const ICON_NAMES = Object.keys(ICONS);

/**
 * Grouped for the picker. A flat grid of 137 icons is a wall — the
 * headings are what make it scannable, and the group label doubles as a search
 * term, so typing "food" finds the fork even though no icon is called that.
 */
export const ICON_GROUPS: { label: string; icons: string[] }[] = [
  { label: 'Home & bills', icons: ["House", "HouseLine", "Buildings", "Lightning", "Drop", "Fire", "WifiHigh", "DeviceMobile", "Television", "Lightbulb", "Plug", "Shower", "Bathtub", "Broom", "Trash", "Wrench", "Hammer", "Toolbox", "Key", "Lock"] },
  { label: 'Food & drink', icons: ["ForkKnife", "Coffee", "BeerBottle", "Wine", "Pizza", "Hamburger", "Carrot", "Egg", "Bread", "Cookie", "IceCream", "Cake", "Champagne", "Martini"] },
  { label: 'Shopping', icons: ["ShoppingCart", "ShoppingBag", "Basket", "Tag", "Receipt", "Gift", "Package", "Storefront", "Handbag", "Scissors"] },
  { label: 'Getting around', icons: ["Car", "Bus", "Train", "Airplane", "AirplaneTilt", "Motorcycle", "Bicycle", "Taxi", "GasPump", "Boat"] },
  { label: 'Health & fitness', icons: ["Barbell", "PersonSimpleRun", "Heartbeat", "FirstAid", "Pill", "Stethoscope", "Tooth", "Eye", "Brain", "SoccerBall", "Basketball"] },
  { label: 'Clothes & self', icons: ["TShirt", "Sneaker", "Dress", "Watch", "Sunglasses"] },
  { label: 'Fun', icons: ["FilmSlate", "MusicNotes", "GameController", "Book", "Books", "Ticket", "Confetti", "Camera", "Palette", "Balloon", "Cigarette"] },
  { label: 'Learning', icons: ["GraduationCap", "Student", "Backpack", "PencilSimple", "Notebook", "Certificate"] },
  { label: 'Money', icons: ["Money", "Coins", "Wallet", "CreditCard", "Bank", "PiggyBank", "HandCoins", "Vault", "Diamond", "ChartLineUp", "TrendUp", "TrendDown", "ChartPieSlice"] },
  { label: 'People & pets', icons: ["Users", "User", "UserCircle", "Baby", "Dog", "Cat", "PawPrint", "Handshake"] },
  { label: 'Work & admin', icons: ["Briefcase", "Signature", "Scales", "Gavel", "Calendar", "Clock", "Bell", "Globe", "Gear"] },
  { label: 'Outdoors', icons: ["Umbrella", "Sun", "CloudRain", "Tree", "Plant", "Flower", "Leaf", "Mountains", "Church", "Warehouse"] },
  { label: 'Other', icons: ["Repeat", "ArrowsClockwise", "ArrowUUpLeft", "ArrowUUpRight", "ArrowsLeftRight", "Star", "Heart", "Note", "DotsThree", "Question"] },
];

export function CategoryIcon({
  name,
  className,
  size = 16,
}: {
  name: string | null | undefined;
  className?: string;
  size?: number;
}) {
  const Icon = (name && ICONS[name]) || Tag;
  return (
    <span
      className={cn(
        "inline-flex items-center justify-center",
        className,
      )}
    >
      <Icon size={size} weight="duotone" />
    </span>
  );
}
